### PR TITLE
Detect iPad when runs iPadOS 13 or up

### PR DESCRIPTION
**Pull request by RTeran**
This PR solves this issue: https://github.com/matthewhudson/current-device/issues/217

### CODE REVIEW

**Comment by winternet-studio** [comment]
Yes, this should be merged. It seems like the only way to fix the issue. It is also the recommended solution on stackoverflow which I guess is where submitter has it from: https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct

**Comment by matthewhudson** [comment]
Now available in v0.10.0!

Thank you both! 

@all-contributors please add @RTeran for code
@all-contributors please add @winternet-studio for review

**Comment by matthewhudson** [comment]
@all-contributors please add @RTeran for code

**Comment by matthewhudson** [comment]
@all-contributors please add @winternet-studio for review

**Comment by matthewhudson** [comment]
@all-contributors please add @winternet-studio for review

**Pull request merged**
